# Use root/example as user/password credentials
version: '3.1'

services:
  blog:
    image: docker.pkg.github.com/visarsylejmani/devops-tp/devops-tp:latest
    restart : unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: blogs

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_URL: mongodb://root:toor@mongo:27017/